### ISSUE TITLE
[Suggestion] Small improvement in CmplxWaveform_t

### ISSUE THREAD

**Issue by dguff** [mjdelgadog/Deconvolution#3]
Hi @mantheys @mjdelgadog , 

the two methods `CmplxWaveform_t::MakeCmplx()` and `CmplxWaveform_t::MakeReAndIm()` at line 237 and 257 respectively are a bit brutal in the sense that they erease the Fourier components after the half of the vector as in the code pasted here. 
```C++
inline void MakeCmplx() {
          for (size_t i=0; i<fCmplx.size()*0.5+1; i++) {
            MakeCmplx(i);
          }
          for (size_t i=fCmplx.size()*0.5+1; i<fCmplx.size(); i++) {
            fCmplx.at(i) = TComplex(0, 0); 
            fRe.at(i) = 0.; 
            fIm.at(i) = 0.;
          }
        }
```
I am not sure this is entirely needed. If you have a moment could you try just change the above function into:
```C++
inline void MakeCmplx() {
          for (size_t i=0; i<fCmplx.size(); i++) {
            MakeCmplx(i);
          }
          return;
        }
```
and see if anything breaks?

**Comment by dguff** [comment]
Aww, I have almost change my mind and wondering now if this is really worth your time. I let yuo decide ;-)

**Comment by mjdelgadog** [comment]
Hi @dguff,  I have done the test with both Wiener and Gauss and everything works, I did not find any change in the results of the deconvolved signals when modifying line 237 and 257 . I will include these changes in the final version :)
